import fs from "node:fs/promises";
import { unlinkSync } from "node:fs";
import path from "node:path";
import { spawn } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";

const url=(process.env.ARCHITECT_URL||"").replace(/\/$/,"");
const id=process.env.ARCHITECT_WORKER_ID;
const token=process.env.ARCHITECT_WORKER_TOKEN;
const repo=process.env.TARGET_REPO;
if(!/^https?:\/\//.test(url)||!/^[ABC]$/.test(id||"")||!token||!repo) throw new Error("Set ARCHITECT_URL, ARCHITECT_WORKER_ID (A/B/C), ARCHITECT_WORKER_TOKEN, and TARGET_REPO.");
const journalFile=path.join(process.cwd(),".architect-runtime",`worker-${id}.json`);
const lockFile=path.join(process.cwd(),".architect-runtime",`worker-${id}.lock`);
const identity=createHash("sha256").update(`${url}\n${id}\n${path.resolve(repo)}`).digest("hex");
let journal={identity,dispatchId:null,phase:null,pid:null,pending:[]};
try {const saved=JSON.parse(await fs.readFile(journalFile,"utf8"));if(saved.identity===identity) journal=saved;} catch {}
await fs.mkdir(path.dirname(lockFile),{recursive:true});
try {const prior=JSON.parse(await fs.readFile(lockFile,"utf8"));if(Number.isInteger(prior.pid)) {try {process.kill(prior.pid,0);throw new Error(`Worker ${id} is already running (PID ${prior.pid}).`);} catch(error) {if(error.code!=="ESRCH") throw error;}}await fs.unlink(lockFile);} catch(error) {if(error.code!=="ENOENT") throw error;}
await fs.writeFile(lockFile,JSON.stringify({pid:process.pid,startedAt:new Date().toISOString()}),{flag:"wx",mode:0o600});
process.once("exit",()=>{try {unlinkSync(lockFile);} catch {}});
let saveQueue=Promise.resolve();
async function save() {const content=JSON.stringify(journal,null,2)+"\n";const write=async()=>{await fs.mkdir(path.dirname(journalFile),{recursive:true});const tmp=`${journalFile}.${randomUUID()}.tmp`;await fs.writeFile(tmp,content,{mode:0o600});await fs.rename(tmp,journalFile);};const next=saveQueue.then(write,write);saveQueue=next.catch(()=>{});await next;}
function print(message) {console.log(`[${new Date().toISOString()}] ${message}`);}
let authRevoked=false;
async function request(action,data) {const response=await fetch(`${url}/worker/v1`,{method:"POST",headers:{"content-type":"application/json","authorization":`Bearer ${token}`,"x-architect-worker":id},body:JSON.stringify({action,data}),signal:AbortSignal.timeout(15000)});const value=await response.json();if(response.status===401) authRevoked=true;if(!response.ok) throw new Error(value.error||`HTTP ${response.status}`);return value;}
function run(command,args,cwd=repo,options={}) {return new Promise((resolve,reject)=>{const child=spawn(command,args,{cwd,shell:options.shell||false,env:options.env||process.env,windowsHide:true});let stdout="",stderr="";child.stdout?.on("data",data=>{stdout=(stdout+data.toString()).slice(-20000);});child.stderr?.on("data",data=>{stderr=(stderr+data.toString()).slice(-20000);});child.on("error",reject);child.on("close",code=>resolve({code,stdout,stderr}));});}
const shell=process.platform==="win32";
async function git(...args) {return run("git",args);}
async function mustGit(...args) {const result=await git(...args);if(result.code!==0) throw new Error(`Git ${args[0]} failed; inspect local Git output.`);return result.stdout.trim();}
let flushPromise=null;
let nextRetryAt=0;
async function report(phase,activity,extra={}) {journal.phase=phase;journal.pending.push({dispatchId:journal.dispatchId,phase,...(activity?{activity}:{}),...extra});await save();await flush();}
async function flush() {if(flushPromise) return flushPromise;if(Date.now()<nextRetryAt) return;flushPromise=(async()=>{while(journal.pending.length) {try {await request("report",journal.pending[0]);journal.pending.shift();await save();} catch(error) {nextRetryAt=Date.now()+5000;print(`Architect update pending: ${error.message}`);break;}}})();try {await flushPromise;}finally {flushPromise=null;}}
async function awaitReceipt() {while(journal.pending.length) {if(authRevoked) throw new Error("Worker connection was revoked before execution.");await new Promise(resolve=>setTimeout(resolve,5000));await flush();}if(authRevoked) throw new Error("Worker connection was revoked before execution.");}
function safePath(value) {if(typeof value!=="string"||/[\r\n\0]/.test(value)) return undefined;const relative=path.isAbsolute(value)?path.relative(repo,value):value;const normalized=relative.replaceAll("\\","/");return normalized.length<180&&!normalized.startsWith("../")&&!normalized.startsWith("/")&&!normalized.includes("/../")&&!/sk-[A-Za-z0-9_-]{12,}/.test(normalized)?normalized:undefined;}
async function prepare(task) {
  if(!/^[A-Za-z0-9][A-Za-z0-9._/-]*$/.test(task.branch)||task.branch.includes("..")||["main","master"].includes(task.branch)||task.branch.endsWith("/")||task.branch.endsWith(".lock")) throw new Error("Unsafe task branch.");
  if((await git("check-ref-format","--branch",task.branch)).code!==0) throw new Error("Invalid task branch.");
  if((await mustGit("status","--porcelain")).trim()) throw new Error("Repository has local changes; preserve them and use a clean checkout.");
  await mustGit("fetch","origin");
  const base=task.baseSha;
  if(!/^[0-9a-f]{40}$/.test(base)||(await git("cat-file","-e",`${base}^{commit}`)).code!==0) throw new Error("Expected base commit unavailable.");
  const remoteMain=(await git("rev-parse","--verify","refs/remotes/origin/main")).stdout.trim()||(await git("rev-parse","--verify","refs/remotes/origin/master")).stdout.trim();
  if(remoteMain!==base) throw new Error("Remote main differs from assigned base; ask Architect to review the task.");
  const local=(await git("rev-parse","--verify",`refs/heads/${task.branch}`));
  const remote=(await git("rev-parse","--verify",`refs/remotes/origin/${task.branch}`));
  if(local.code===0&&local.stdout.trim()!==base) throw new Error("Local task branch already contains work; inspect it manually.");
  if(remote.code===0&&remote.stdout.trim()!==base) throw new Error("Remote task branch already contains work; inspect it manually.");
  if(local.code===0) await mustGit("switch",task.branch);
  else await mustGit("switch","-c",task.branch,base);
  if((await mustGit("rev-parse","HEAD"))!==base) throw new Error("Branch base mismatch.");
}
function prompt(task) {return `Read AGENTS.md and relevant .architect project files before editing.\nASSIGNMENT\n${task.id} — ${task.title}\nOBJECTIVE\n${task.objective}\nACCEPTANCE\n${task.acceptance.map(x=>`- ${x}`).join("\n")||"- Meet the objective"}\nOWNED PATHS\n${task.ownedPaths.map(x=>`- ${x}`).join("\n")||"- No explicit list"}\nAVOID PATHS\n${task.avoidPaths.map(x=>`- ${x}`).join("\n")||"- No explicit list"}\nDEPENDENCIES\n${task.dependencies.map(x=>`- ${x.title} (${x.id})`).join("\n")||"- None"}\nRULES\n- Work only on this assignment.\n- Do not start another milestone/task.\n- Do not change architecture unless required and explicitly approved.\n- Do not invent secrets.\n- Run relevant tests.\n- Leave repository in reviewable state.\n`;}
async function codex(task) {const env={...process.env};for(const key of Object.keys(env)) if(key.startsWith("ARCHITECT_WORKER_")||key==="ARCHITECT_URL") delete env[key];return new Promise((resolve,reject)=>{const child=spawn("codex",["exec","--json","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-"],{cwd:repo,shell,env,windowsHide:true});journal.pid=child.pid;save().catch(reject);let partial="",eventReports=Promise.resolve(),eventCount=0;child.stdout?.on("data",chunk=>{partial+=chunk.toString();const lines=partial.split(/\r?\n/);partial=lines.pop()||"";for(const line of lines) {if(eventCount>=20) continue;try {const event=JSON.parse(line);const changed=safePath(event.item?.file_path||event.item?.path);if(changed) {eventCount++;eventReports=eventReports.then(()=>report("working","editing",{path:changed}));}} catch {}}});child.stderr?.on("data",()=>{});child.on("error",reject);child.on("close",async code=>{await eventReports.catch(()=>{});journal.pid=null;await save();resolve({code});});child.stdin?.end(prompt(task));});}
async function scanSecrets() {const files=(await mustGit("ls-files","--cached","--others","--exclude-standard","-z")).split("\0").filter(Boolean);const pattern=/(sk-[A-Za-z0-9_-]{12,}|(?:api[_-]?key|secret|token)\s*[=:]\s*["']?[A-Za-z0-9_-]{12,})/i;for(const file of files) {if(/(^|\/)(?:\.env(?:\..+)?|id_rsa|id_ed25519)$|\.(?:pem|p12|pfx)$/i.test(file.replaceAll("\\","/"))) return false;const full=path.join(repo,file);try {if((await fs.lstat(full)).isFile()&&pattern.test(await fs.readFile(full,"utf8"))) return false;} catch(error) {if(error.code!=="ENOENT") return false;}}return true;}
async function verify() {let pkg;try {pkg=JSON.parse(await fs.readFile(path.join(repo,"package.json"),"utf8"));} catch {return {ok:false,checks:[{name:"npm project",ok:false}]};}const checks=[];if((pkg.packageManager&&!pkg.packageManager.startsWith("npm@"))||await fs.stat(path.join(repo,"pnpm-lock.yaml")).then(()=>true,()=>false)||await fs.stat(path.join(repo,"yarn.lock")).then(()=>true,()=>false)) checks.push({name:"npm project",ok:false});else {let configured=0;for(const name of ["typecheck","test","build"]) {if(!pkg.scripts?.[name]) continue;configured++;print(`Running ${name}...`);await report("verifying",name==="build"?"build_started":"tests_started");const result=await run("npm",["run",name],repo,{shell,env:name==="build"?{...process.env,NODE_ENV:"production"}:process.env});checks.push({name,ok:result.code===0});if(result.code!==0) break;await report("verifying",name==="build"?"build_passed":"tests_passed");}if(!configured) checks.push({name:"npm scripts",ok:false});}checks.push({name:"Secret scan",ok:await scanSecrets()});return {ok:checks.every(c=>c.ok),checks};}
async function changedPaths(base) {return (await mustGit("diff","--name-only",`${base}...HEAD`)).split(/\r?\n/).filter(Boolean).map(safePath).filter(Boolean).slice(0,200);}
async function execute(dispatch) {const task=dispatch.task;journal={identity,dispatchId:dispatch.id,phase:"assigned",pid:null,pending:[]};await save();try {await report("received","received");await awaitReceipt();await prepare(task);await report("working","codex_started");print(`Task ${task.title} | branch ${task.branch} | WORKING`);const result=await codex(task);if(result.code!==0) {await report("failed","failed");print("FAILED: Codex execution failed. Local work preserved.");return;}await report("verifying","verification_started");const verification=await verify();if(!verification.ok) {await report("blocked","verification_failed",{checks:verification.checks});print("BLOCKED: verification failed. Local work preserved.");return;}await report("verifying","verification_passed",{checks:verification.checks});if(!(await scanSecrets())) throw new Error("Secret scan failed before commit.");await report("committing");const status=await mustGit("status","--porcelain");if(!status.trim()) throw new Error("Codex produced no changes.");await mustGit("add","-A");if(!(await scanSecrets())) throw new Error("Secret scan failed after staging.");const identityName=await git("var","GIT_AUTHOR_IDENT");if(identityName.code!==0) {await report("action_required","failed");print(`ACTION REQUIRED: Git identity not configured on Worker ${id}.`);return;}await mustGit("commit","-m",`feat(${task.id.slice(0,8)}): ${task.title.replace(/[\r\n]/g," ").slice(0,70)}`);const commit=await mustGit("rev-parse","HEAD");const paths=await changedPaths(task.baseSha);if((await mustGit("status","--porcelain")).trim()) throw new Error("Working tree not clean after commit.");await report("pushing","commit_created",{commit,changedPaths:paths});await report("pushing","push_started");const pushed=await git("push","origin",`HEAD:refs/heads/${task.branch}`);if(pushed.code!==0) {await report("local_result_ready","failed",{commit,checks:verification.checks,changedPaths:paths});print(`LOCAL RESULT READY: push failed; local commit ${commit}.`);return;}await report("ready_for_review","push_completed",{commit,checks:verification.checks,changedPaths:paths});print(journal.pending.length?`LOCAL PUSH COMPLETE; Architect status pending: ${task.branch} ${commit}`:`READY FOR REVIEW: ${task.branch} ${commit}`);} catch(error) {print(`ACTION REQUIRED: ${error.message}. Repository preserved.`);if(authRevoked) {process.exit(1);}try {await report("action_required","failed");} catch {}}}
async function validate() {if(!(await fs.stat(repo).catch(()=>null))?.isDirectory()) throw new Error("TARGET_REPO does not exist.");if((await git("rev-parse","--is-inside-work-tree")).stdout.trim()!=="true") throw new Error("TARGET_REPO is not a Git worktree.");if(path.resolve((await mustGit("rev-parse","--show-toplevel")))!==path.resolve(repo)) throw new Error("TARGET_REPO must be the Git worktree root.");if((await run("codex",["--version"],repo,{shell})).code!==0) throw new Error("Codex executable unavailable.");if((await git("--version")).code!==0) throw new Error("Git executable unavailable.");const unresolved=journal.dispatchId&&!(["ready_for_review","blocked","failed","local_result_ready","action_required"].includes(journal.phase));await request("poll",{ready:!unresolved,codex:true,git:true,...(journal.dispatchId?{currentDispatchId:journal.dispatchId}:{})});}
await validate();print(`ARCHITECT WORKER ${id} | Architect CONNECTED | Codex AVAILABLE | Git AVAILABLE | Repository ${repo}`);
if(journal.dispatchId&&!["ready_for_review","blocked","failed","local_result_ready","action_required"].includes(journal.phase)) {print("Prior assignment may still be running. No duplicate execution will start; inspect local journal and Codex process.");journal.pending.push({dispatchId:journal.dispatchId,phase:"action_required",activity:"reconnected"});await save();}
let executing=false;while(true) {try {await flush();const result=await request("poll",{ready:!executing&&(!journal.dispatchId||["ready_for_review","blocked","failed","local_result_ready","action_required"].includes(journal.phase)),codex:true,git:true,...(journal.dispatchId?{currentDispatchId:journal.dispatchId}:{})});if(result.dispatch&&result.dispatch.id!==journal.dispatchId&&!executing) {executing=true;execute(result.dispatch).finally(()=>{executing=false;});}else if(!executing) print("Waiting for assignment...");} catch(error) {print(`Disconnected: ${error.message}. Retrying; local execution continues.`);}await new Promise(resolve=>setTimeout(resolve,5000));}
